# -*- mode: ruby -*-
# vi: set ft=ruby :
@ansible_home = "/home/vagrant/.ansible"

Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-18.04"

  # Copy the Ansible playbook over to the guest machine, run rsync-auto to automatically
  # pull in the latest changes while a VM is running.
  config.vm.synced_folder "../", "#{@ansible_home}/roles/ansible-vault", type: 'rsync'

  # The working ansible directory created by ansible_local is owned by root
  config.vm.provision "shell", inline: "chown vagrant:vagrant #{@ansible_home}"

  config.vm.network "private_network", ip: "192.168.50.4"

  # Expose Vault UI on port 8200
  config.vm.network "forwarded_port", guest: 8200, host: 8200, auto_correct: true

  # Run the Ansible provisioner
  config.vm.provision "ansible_local" do |ansible|
    ansible.install_mode = "pip"
    ansible.playbook = "test.yml"
  end
end